//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinksMediaCorpUtility
{
    using System;   
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinksMediaCorp.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string ActivityTargetType {
            get {
                return ResourceManager.GetString("ActivityTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string ActivityUrl {
            get {
                return ResourceManager.GetString("ActivityUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter  a challenge description!.
        /// </summary>
        public static string ChallengeDescriptionMsg {
            get {
                return ResourceManager.GetString("ChallengeDescriptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter  a challenge name!.
        /// </summary>
        public static string ChallengeNameMsg {
            get {
                return ResourceManager.GetString("ChallengeNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHALLENGE OF THE DAY.
        /// </summary>
        public static string ChallengeOfTheDayLabel {
            get {
                return ResourceManager.GetString("ChallengeOfTheDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        public static string ChallengeTargetType {
            get {
                return ResourceManager.GetString("ChallengeTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges.
        /// </summary>
        public static string ChallengeUrl {
            get {
                return ResourceManager.GetString("ChallengeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City field is required..
        /// </summary>
        public static string CityNotSelected {
            get {
                return ResourceManager.GetString("CityNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record successfully deleted..
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exist!.
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team already exist!.
        /// </summary>
        public static string DuplicateTeam {
            get {
                return ResourceManager.GetString("DuplicateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist!.
        /// </summary>
        public static string DuplicateUser {
            get {
                return ResourceManager.GetString("DuplicateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id already exist..
        /// </summary>
        public static string EmailAlreadyExist {
            get {
                return ResourceManager.GetString("EmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password!.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a username!.
        /// </summary>
        public static string EnterUserName {
            get {
                return ResourceManager.GetString("EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during password change.
        /// </summary>
        public static string ErrorPwdChange {
            get {
                return ResourceManager.GetString("ErrorPwdChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to videos/exerciseThumbnails/.
        /// </summary>
        public static string ExerciseThumbnailDirectory {
            get {
                return ResourceManager.GetString("ExerciseThumbnailDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to videos/exercise/.
        /// </summary>
        public static string ExerciseVideoDirectory {
            get {
                return ResourceManager.GetString("ExerciseVideoDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has started following you..
        /// </summary>
        public static string FollowingNTMsg {
            get {
                return ResourceManager.GetString("FollowingNTMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followings.
        /// </summary>
        public static string FollowingsTargetType {
            get {
                return ResourceManager.GetString("FollowingsTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string FreeFormChallengeTypeId {
            get {
                return ResourceManager.GetString("FreeFormChallengeTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string FreeFormChallengeWellnessId {
            get {
                return ResourceManager.GetString("FreeFormChallengeWellnessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string FreeFormChallengeWorkoutId {
            get {
                return ResourceManager.GetString("FreeFormChallengeWorkoutId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} challenged you..
        /// </summary>
        public static string FriendNotificationMsg {
            get {
                return ResourceManager.GetString("FriendNotificationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old password is incorrect!.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Username or Password!!.
        /// </summary>
        public static string IncorrectUserNameOrPassword {
            get {
                return ResourceManager.GetString("IncorrectUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Height in Inches.
        /// </summary>
        public static string InvalidHeight {
            get {
                return ResourceManager.GetString("InvalidHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Hour(s)..
        /// </summary>
        public static string InvalidHours {
            get {
                return ResourceManager.GetString("InvalidHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Minute(s)..
        /// </summary>
        public static string InvalidMinutes {
            get {
                return ResourceManager.GetString("InvalidMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid HS(s)..
        /// </summary>
        public static string InvalidMS {
            get {
                return ResourceManager.GetString("InvalidMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number of session!.
        /// </summary>
        public static string InvalidNumberOfTrainingSession {
            get {
                return ResourceManager.GetString("InvalidNumberOfTrainingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid numeric value.
        /// </summary>
        public static string InvalidNumeric {
            get {
                return ResourceManager.GetString("InvalidNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be min 4 and max 10 characters in length.
        /// </summary>
        public static string InvalidPasswordLength {
            get {
                return ResourceManager.GetString("InvalidPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White space not allowed in Password..
        /// </summary>
        public static string InvalidPasswordWhiteSpace {
            get {
                return ResourceManager.GetString("InvalidPasswordWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid reps.
        /// </summary>
        public static string InvalidReps {
            get {
                return ResourceManager.GetString("InvalidReps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Second(s)..
        /// </summary>
        public static string InvalidSeconds {
            get {
                return ResourceManager.GetString("InvalidSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer Type should be  max 16 characters in length!.
        /// </summary>
        public static string InvalidTrainerTypeLength {
            get {
                return ResourceManager.GetString("InvalidTrainerTypeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a session amount!.
        /// </summary>
        public static string InvalidTrainingSessionAmount {
            get {
                return ResourceManager.GetString("InvalidTrainingSessionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Weight in lbs.
        /// </summary>
        public static string InvalidWeight {
            get {
                return ResourceManager.GetString("InvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string InvalidWeightForMan {
            get {
                return ResourceManager.GetString("InvalidWeightForMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid 5 digit zip code..
        /// </summary>
        public static string InvalidZip {
            get {
                return ResourceManager.GetString("InvalidZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has joined your team..
        /// </summary>
        public static string JoinTeamNotificationMsg {
            get {
                return ResourceManager.GetString("JoinTeamNotificationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Jpg.
        /// </summary>
        public static string JpgImageExtension {
            get {
                return ResourceManager.GetString("JpgImageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is incorrect..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginUserName.
        /// </summary>
        public static string LoginUserName {
            get {
                return ResourceManager.GetString("LoginUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Successfully..
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainUrlText {
            get {
                return ResourceManager.GetString("MainUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string MediaTypeImage {
            get {
                return ResourceManager.GetString("MediaTypeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string MediaTypeVideo {
            get {
                return ResourceManager.GetString("MediaTypeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  and {1} other {2} started following you..
        /// </summary>
        public static string MoreFollowingNTMsg {
            get {
                return ResourceManager.GetString("MoreFollowingNTMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  and {1} other {2} have boomed your post..
        /// </summary>
        public static string MoreNewsFeedBoomedMsg {
            get {
                return ResourceManager.GetString("MoreNewsFeedBoomedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  and {1} other {2} have commented on your post..
        /// </summary>
        public static string MoreNewsFeedCommentedMsg {
            get {
                return ResourceManager.GetString("MoreNewsFeedCommentedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  and {1} other {2} have also commented on a post..
        /// </summary>
        public static string MorePostCommentReplyMsg {
            get {
                return ResourceManager.GetString("MorePostCommentReplyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  and {1} other {2} have posted on your profile..
        /// </summary>
        public static string MoreProfilePostNTMsg {
            get {
                return ResourceManager.GetString("MoreProfilePostNTMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  and {1} other {2} have boomed your result..
        /// </summary>
        public static string MoreResultBoomedMsg {
            get {
                return ResourceManager.GetString("MoreResultBoomedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  and {1} other {2} have commented on your result..
        /// </summary>
        public static string MoreResultCommentedMsg {
            get {
                return ResourceManager.GetString("MoreResultCommentedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  and {1} other {2} have also commented on a result you have commented on..
        /// </summary>
        public static string MoreResultCommentReplyMsg {
            get {
                return ResourceManager.GetString("MoreResultCommentReplyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string msgat {
            get {
                return ResourceManager.GetString("msgat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string msgOther {
            get {
                return ResourceManager.GetString("msgOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string msgToday {
            get {
                return ResourceManager.GetString("msgToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string msgYesterday {
            get {
                return ResourceManager.GetString("msgYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY PRIMARY TRAINER.
        /// </summary>
        public static string MyPrimaryTrainer {
            get {
                return ResourceManager.GetString("MyPrimaryTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyTeam.
        /// </summary>
        public static string MyTeamTargetType {
            get {
                return ResourceManager.GetString("MyTeamTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has boomed your post..
        /// </summary>
        public static string NewsFeedBoomedMsg {
            get {
                return ResourceManager.GetString("NewsFeedBoomedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has commented on your post..
        /// </summary>
        public static string NewsFeedCommentedMsg {
            get {
                return ResourceManager.GetString("NewsFeedCommentedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotAvailable.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people.
        /// </summary>
        public static string NtPeople {
            get {
                return ResourceManager.GetString("NtPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to person.
        /// </summary>
        public static string NtPerson {
            get {
                return ResourceManager.GetString("NtPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/4.
        /// </summary>
        public static string OneByFour {
            get {
                return ResourceManager.GetString("OneByFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/3.
        /// </summary>
        public static string OneByThree {
            get {
                return ResourceManager.GetString("OneByThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/2.
        /// </summary>
        public static string OneByTwo {
            get {
                return ResourceManager.GetString("OneByTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully!.
        /// </summary>
        public static string PasswordChangeSuccess {
            get {
                return ResourceManager.GetString("PasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo successfully uploaded..
        /// </summary>
        public static string PhotoSuccessfullyUploaded {
            get {
                return ResourceManager.GetString("PhotoSuccessfullyUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pic.
        /// </summary>
        public static string PicMessageType {
            get {
                return ResourceManager.GetString("PicMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has also commented on a post..
        /// </summary>
        public static string PostCommentReplyMsg {
            get {
                return ResourceManager.GetString("PostCommentReplyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreviousUrl.
        /// </summary>
        public static string PreviousUrl {
            get {
                return ResourceManager.GetString("PreviousUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/profilepic/.
        /// </summary>
        public static string ProfilePicDirectory {
            get {
                return ResourceManager.GetString("ProfilePicDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has posted on your profile..
        /// </summary>
        public static string ProfilePostNTMsg {
            get {
                return ResourceManager.GetString("ProfilePostNTMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string ProgramUrl {
            get {
                return ResourceManager.GetString("ProgramUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully!.
        /// </summary>
        public static string PwdChangeSuccessfully {
            get {
                return ResourceManager.GetString("PwdChangeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter password!.
        /// </summary>
        public static string ReEnterPassword {
            get {
                return ResourceManager.GetString("ReEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has boomed your result..
        /// </summary>
        public static string ResultBoomedMsg {
            get {
                return ResourceManager.GetString("ResultBoomedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has commented on your result..
        /// </summary>
        public static string ResultCommentedMsg {
            get {
                return ResourceManager.GetString("ResultCommentedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has also commented on a result you have commented on..
        /// </summary>
        public static string ResultCommentReplyMsg {
            get {
                return ResourceManager.GetString("ResultCommentReplyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/result/.
        /// </summary>
        public static string ResultPicDirectory {
            get {
                return ResourceManager.GetString("ResultPicDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to videos/result/.
        /// </summary>
        public static string ResultVideoDirectory {
            get {
                return ResourceManager.GetString("ResultVideoDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Draft.
        /// </summary>
        public static string SavetoDraft {
            get {
                return ResourceManager.GetString("SavetoDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on Server....
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has been expired..
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPONSOR CHALLENGE.
        /// </summary>
        public static string SponsorChallengeLebel {
            get {
                return ResourceManager.GetString("SponsorChallengeLebel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The State field is required..
        /// </summary>
        public static string StateNotSelected {
            get {
                return ResourceManager.GetString("StateNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record successfully submitted!.
        /// </summary>
        public static string SubmitMessage {
            get {
                return ResourceManager.GetString("SubmitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        public static string TargetTypeChallenge {
            get {
                return ResourceManager.GetString("TargetTypeChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (default).
        /// </summary>
        public static string TeamDefaultText {
            get {
                return ResourceManager.GetString("TeamDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string TeamTargetType {
            get {
                return ResourceManager.GetString("TeamTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string TeamUrl {
            get {
                return ResourceManager.GetString("TeamUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextMessageType {
            get {
                return ResourceManager.GetString("TextMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3/4.
        /// </summary>
        public static string ThreeByFour {
            get {
                return ResourceManager.GetString("ThreeByFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} challenged you!.
        /// </summary>
        public static string TrainerNotificationMsg {
            get {
                return ResourceManager.GetString("TrainerNotificationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Trainer field is required..
        /// </summary>
        public static string TrainerNotSelected {
            get {
                return ResourceManager.GetString("TrainerNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has posted something..
        /// </summary>
        public static string TrainerPostToUserMsg {
            get {
                return ResourceManager.GetString("TrainerPostToUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~images\\Profile_Pic.
        /// </summary>
        public static string TrainerProfile {
            get {
                return ResourceManager.GetString("TrainerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainers.
        /// </summary>
        public static string TrainerUrl {
            get {
                return ResourceManager.GetString("TrainerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2/4.
        /// </summary>
        public static string TwoByFour {
            get {
                return ResourceManager.GetString("TwoByFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2/3.
        /// </summary>
        public static string TwoByThree {
            get {
                return ResourceManager.GetString("TwoByThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record successfully updated..
        /// </summary>
        public static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exist..
        /// </summary>
        public static string UserAlreadyExist {
            get {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserTargetType {
            get {
                return ResourceManager.GetString("UserTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string UserTypeAdmin {
            get {
                return ResourceManager.GetString("UserTypeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string UserTypeTeam {
            get {
                return ResourceManager.GetString("UserTypeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trainer.
        /// </summary>
        public static string UserTypeTrainer {
            get {
                return ResourceManager.GetString("UserTypeTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string UserTypeUser {
            get {
                return ResourceManager.GetString("UserTypeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserUrl {
            get {
                return ResourceManager.GetString("UserUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miles.
        /// </summary>
        public static string VariableUnitmiles {
            get {
                return ResourceManager.GetString("VariableUnitmiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string VariableUnitminutes {
            get {
                return ResourceManager.GetString("VariableUnitminutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string VariableUnitTypeSecond {
            get {
                return ResourceManager.GetString("VariableUnitTypeSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string VideoMessageType {
            get {
                return ResourceManager.GetString("VideoMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video successfully uploaded..
        /// </summary>
        public static string VideoSuccessfullyUploaded {
            get {
                return ResourceManager.GetString("VideoSuccessfullyUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is incorrect..
        /// </summary>
        public static string WrongUserPassword {
            get {
                return ResourceManager.GetString("WrongUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid 5 digit zip code!.
        /// </summary>
        public static string ZipCodeNotExist {
            get {
                return ResourceManager.GetString("ZipCodeNotExist", resourceCulture);
            }
        }
    }
}
