CREATE TABLE [dbo].[tblTeam] (
    [TeamId]                   INT            IDENTITY (1, 1) NOT NULL,
    [TeamName]                 NVARCHAR (MAX) NOT NULL,
    [IsDefaultTeam]            BIT            CONSTRAINT [DF_tblTeam_IsDefaultTeam] DEFAULT ((0)) NOT NULL,
    [Address]                  NVARCHAR (MAX) NULL,
    [City]                     INT            NOT NULL,
    [State]                    NVARCHAR (MAX) NOT NULL,
    [ZipCode]                  NVARCHAR (MAX) NULL,
    [EmailId]                  NVARCHAR (MAX) NOT NULL,
    [PhoneNumber]              NVARCHAR (MAX) NULL,
    [ProfileImageUrl]          NVARCHAR (MAX) NULL,
    [PremiumImageUrl]          NVARCHAR (MAX) NULL,
    [LoggedIn]                 BIT            NULL,
    [CreatedBy]                INT            NOT NULL,
    [CreatedDate]              DATETIME       NULL,
    [ModifiedBy]               INT            NULL,
    [ModifiedDate]             DATETIME       NULL,
    [UniqueTeamId]             INT            NULL,
    [OnboardingExeciseVideoId] INT            CONSTRAINT [DF_tblTeam_OnboardingExeciseVideoId] DEFAULT ((0)) NOT NULL,
    [FitcomtestChallengeId1]   INT            CONSTRAINT [DF_tblTeam_FitcomtestChallengeId1] DEFAULT ((0)) NOT NULL,
    [FitcomtestChallengeId2]   INT            CONSTRAINT [DF_tblTeam_FitcomtestChallengeId2] DEFAULT ((0)) NOT NULL,
    [BeginnerProgramId]        INT            CONSTRAINT [DF_tblTeam_BeginnerProgramId] DEFAULT ((0)) NOT NULL,
    [AdvIntProgramId1]         INT            CONSTRAINT [DF_tblTeam_AdvIntProgramId1] DEFAULT ((0)) NOT NULL,
    [AdvIntProgramId2]         INT            CONSTRAINT [DF_tblTeam_AdvIntProgramId2] DEFAULT ((0)) NOT NULL,
    [AdvIntProgramId3]         INT            CONSTRAINT [DF_tblTeam_AdvIntProgramId3] DEFAULT ((0)) NOT NULL,
    [Nutrition1ImageUrl]       NVARCHAR (MAX) NULL,
    [Nutrition1HyerLink]       NVARCHAR (MAX) NULL,
    [Nutrition2ImageUrl]       NVARCHAR (MAX) NULL,
    [Nutrition2HyerLink]       NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_tblTeam] PRIMARY KEY CLUSTERED ([TeamId] ASC)
);

